# Introduction

> Note: If this is a pdf version of the thesis, the interactive graphics showcased in Section 4. Use will be rendered as static snapshots only, due to the limitations of the pdf format. The thesis is also available in fully interactive HTML format, and the source code for the Typescript version of the `plotscape` package can be found at https://github.com/bartonicek/plotscape

Humans learn about the world around them by interacting with it. Likewise, if we want to learn about our data, we need efficient and principled ways of interacting with it. Currently, there are many options for interactive data visualization exist as packages within the R ecosystem. However, a large portion of these packages tend to suffer from a common set of drawbacks. Most importantly, while many of these packages make it easy to create isolated interactive plots with surface-level kinds of interactivity, setting up more interesting interactive figures with interaction between multiple plots is often challenging and requires a deep knowledge of the API. Furthermore, the design philosophy behind these packages seems to favor data presentation over data exploration. Finally, while these packages offer a large hosts of features, many of these may not be conducive to learning from data effectively. As such, there is a need for a general purpose interactive data visualization system that allows for fast and effective exploratory data analysis (EDA). The purpose of the present thesis is to develop and present a prototype of such a system in `plotscape`.    