# Literature Review

Interactive data visualization is popular. Interactive figures appear everywhere, from news articles, to business-analytic dashboards, to science communication outlets such as journal websites and personal blogs. Yet, despite the popularity, there does seem to be a lot of unanswered questions about them. 

## What even is interactivity?

>If it looks like a duck, swims like a duck, and quacks like a duck, then it probably is a duck.
>
> [Duck Test](https://en.wikipedia.org/wiki/Duck_test) entry, [@wikipedia2022] 

What is an interactive visualization? It may seen like a silly question. So many people talk about interactive visualizations, then, surely, they must all be referring to the same thing, right? Unfortunately, that does not seem to be the case. When researchers and applied practitioners say "interactive visualization", they tend to refer to many different things in many different contexts.  

First off, it is necessary to disambiguate whether we refer to "interactive visualization" as a noun, a thing that exists, or to "interactive visualization" as a process, an action undertaken by a human being. Pike et al. [-@pike2009science] note that "interaction" is an overloaded term that can refer to either the concrete set of tools through which users manipulate the visual information or to the more abstract "human interaction with information" - the back-and-forth between the user and the visual information presented to them [see also @yi2007toward]. Which definition you use depends on the field: statisticians and computer scientists primarily talk about interactive visualizations as things, whereas researchers in the fields of cognitive science and human-computer interaction tend to emphasize interactive visualization as action, although there is also considerable overlap. While the cognitive aspect of humans interacting with visual information is definitely interesting, for the purpose of this thesis, I will mainly talk about "interactive visualizations" as things, i.e. visual objects that live on a computer screen.

Yet, even if we narrow down the focus on interactive visualizations as visual objects, there is still a lot of ambiguity, and some researchers define interactive visualizations very broadly. For example, there are those that talk about interactive visualizations as any visualizations can be actively manipulated by the user [@brodbeck2009]. To others, the key thing about interactivity is time, or rather, the lag between the user's input and changes to the visualization, with less lag meaning more interactivity [@becker1987brushing; @buja1996interactive]. Some even make the distinction between "interactive" and "dynamic" manipulation, where interactive manipulation happens discretely such as by pressing a button or selecting an item from a drop-down menu, whereas dynamic manipulation happens continuously, in real-time, for example by smoothly moving a slider or by clicking-and-dragging [@rheingans2002we; @jankun2007model]. What these two definitions - which I will label the "basic" and "temporal" - have in common is that they impose relatively little restrictions on what can be considered an interactive visualization. For example, one could argue if the user runs a code from a command line to generate a new plot, this could be considered interactive visualization, under these definitions.  

In contrast, other researchers consider the category of "interactive visualizations" to be much narrower. For many, the defining features are the ability to query different parts of the dataset (by e.g. zooming, panning, and filtering), and the propagation of changes between connected or "linked" parts of the visualization [@kehrer2012generic; @buja1996interactive; @keim2002information; @unwin1999mar]. Similarly, in Visual Analytics (VA) research, a distinction is made between "surface-level" and "parametric" interactions, where surface-level interactions manipulate attributes of the visual domain only (e.g. zooming and panning), whereas parametric interactions manipulate attributes of mathematical models underlying the visualization [@leman2013visual]. These definitions of interactivity - which I will label "filtering", "linked", and "parametric" - can describe considerably more complex objects. Specifically, while filtering interactions like zooming and panning can be implemented by manipulating graphical attributes (i.e. coordinate system) of the visualization only, linked and parametric interactions require special underlying data structures in all but the most simple cases. For example, in a prototypical case of an interactive feature called "linked brushing", the user can click-and-drag to select points on a scatter plot and the selection will then be reflected in another plot, for example, by drawing a bars in a barplot with the heights corresponding to the number of the selected points. This requires the barplot to be "aware" of which cases in the data (corresponding to the points in the scatterplot) have been selected, and it has to respond to these changes online, in real time, by recomputing the height of the newly drawn bars. 

Put simply, the term "interactive visualization" seems to mean a lot of different things to a lot of different people. Below, in Table \@ref(tab:definitions), I have attempted to summarize the main types of interactivity in data visualizations. This list is not supposed to be exhaustive as more complete and detailed taxonomies of interactive visualizations have been described [see @yi2007toward]. Instead, the point of this list is to provide a rough sketch of the space interactive visualizations live in: 

```{r definitions, echo = FALSE}

tab <- read.csv('tables/definitions.csv')
colnames(tab) <- c("Type", "Short definition", "Details")
knitr::kable(tab, longtable = TRUE, caption = 'Types of interactivity')

```

Using the term "interactive" to cover such a wide range of visualizations leads to ambiguity. For example, imagine we have a single scatterplot. The user can click-and-drag this scatterplot to highlight certain points (i.e. brush). Should this scatterplot be considered "interactive"? Under the most basic definition, yes, since the user *can* affect the visualization through interaction. However, some researcher may not be satisfied with that and may ask us to tell them whether the visualization meets linked or parametric defition of interactivity. With only a single plot, there's nowhere for our interactions to propagate to, and changing the color of individual points can hardly be considered a change to a mathematical model, so our verdict would then have to be "not interactive". What if the researcher was a fan of the temporal definition? If we assume the results of the user's interactions render smoothly enough, we could certainly call the plot interactive. However, what if more data is added to the plot and the user now has to wait several hundreds of milliseconds, or even seconds, before the interaction is rendered? Does an interactive visualization stop being interactive as a result of our computational resources being reduced? Therefore, even with such a simple example, there are many arguments that could be made for and against calling a plot interactive.



## Types of Interactive Features



## Current Options for Interactive Visualizations

It may seem that the conceptual ambiguity about what counts as an "interactive visualization" is just an academic matter, however, it has real consequences for the software implementations. For example, the [R Graph Gallery entry on Interactive Charts](https://r-graph-gallery.com/interactive-charts.html) [@holtz2022interactive] several visualizations which allow for surface-level user interactions such zooming, panning, hovering, 3D rotation, and node repositioning within a network graph. However, in all of the examples, the user only affect graphical attributes of a single plot, and so these visualizations do not meet the linked and parametric definitions of interactivity. In contrast, the [Plotly Dash documentation page on Interactive Visualizations](https://dash.plotly.com/interactive-graphing) [@bibentry2022plotly] features examples of linked hovering and cross-filtering, i.e. examples of linked interactivity. However, it should be noted that vast majority of visualizations in the [Plotly R Open Source Graphing Library documentation page](https://plotly.com/r/) [@bibentry2022plotly] allow only for surface-level interactions. Somewhat differently again, [VegaLite Gallery pages on Interactive Charts](https://vega.github.io/vega-lite/examples/#interactive-charts) and [Interactive Multiview Displays](https://vega.github.io/vega-lite/examples/#interactive-multi-view-displays)  [@bibentry2022vegalite] feature many examples, however, only a few meet the linked or parametric definitions.

What all of the packages listed above have in common is that most visualizations feature only surface-level interactivity, and the ones that feature examples of linked or parametric interactivity require quite extensive setup.  

