# Conclusion

## Concluding remarks

Currently, most available software for interactive data visualization is geared towards three things: 1) presentation, not exploration, 2) generality rather than ease of use, and 3) shallow types of interactivity rather than more interesting ones. While it is important to have general frameworks that computer science specialists can use to build attractive data presentations, the absence of alternatives means that applied researchers and data scientist lack easy-to-use tools for understanding their data and deriving insights effectively. It is hard to to quantify just how much of an opportunity cost this presents. 

The goal of the present thesis was to develop a prototype or a proof-of-concept of an interactive data visualization system that would fill the data exploration niche outlined above. Further, it was to do so in line with solid data visualization principles. I believe that I have created a prototype of such a system in `plotscape`, which, while still far from being completely general and robust, is already able to produce a range of interesting and useful visualization. 

## Future Directions

There is a variety of features that could still be implemented. Currently, two types of data representations are supported: bars and points. Using just these two representations, I have implemented the following types of wrapper plots: scatterplot, bubbleplot, barplot, histogram, squareplot/square bubble plot, and square heatmap. However, using the Wrangler and Cast framework, it should not be difficult to implement other types of plots. To make even more types of plots available, it would be worthwhile to implement other types of representations such as lines and polygons. Further, it could be very useful to add more sophisticated, derived data representations such as linear/smooth fits. On a more abstract level, it may also be worthwhile to develop the logic behind the Wrangler-and-Cast framework more deeply. Conversely, while there are some concrete features such as color and outline of representations that can be modified, many features of the `plotscape` plots or scenes are currently either hard-coded or automatically derived: it would be useful to add user customization for graphical features such as axis text/title/ticks, margins, etc... Finally, it is important to mention that `plotscape` is still in a very experimental state at the present date - to make it into a full R/JavaScript package, it would be necessary to round out the documentation, add proper error messages/handling, etc...

To summarize, I have created a proof-of-concept interactive data visualization system geared towards data exploration and ease of use. The package is directly callable from R and, using few core elements, it can already be used to create a fairly wide range of interesting and useful interactive visualizations. As such, I believe it has great potential to bring great benefit to applied researchers. However, to make it into a fully-fledged and roboust interactive visualization system, more work would be required.