
# Appendix

#### Encapsulation in DOP {#dop-encapsulation}

For example, here's how we can emulate private property access in JavaScript using Proxy. We create a namespace with a single constructor function that takes an object and a namespace and returns a proxy of the object which prevents access to the object fields outside of the namespace:

```{ts}
// Private.ts
export namespace Private {
  export function of<T extends Object>(object: T, namespace: Object) {
    return new Proxy(object, {
      get: (t, k, e) => (e === namespace ? Reflect.get(t, k) : undefined),
      set: (t, k, v, e) => (e === namespace ? (Reflect.set(t, k, v), true) : true),
    });
  }
}
```

We can then use this namespace in the constructor functions of data we want to make private:

```{ts}
import { Private } from "./Private.ts"

// Data type - container for stateful data
interface User {
  firstName: string;
  lastName: string;
}

// Code module - consists of stateless functions
namespace User {
  // Constructor function
  export function of(firstName: string, lastName: string): User {
    return Private.of({firstName, lastName}, User);
  }
  
  // Internal getter function
  function get(user: User, key: keyof User) {
    return Reflect.get(user, key, User);
  }
  // We could do the same thing for a private setter
  
  export function getFullName(user: User) {
    return get(user, `firstName`) + ` ` + get(user, `lastName`);
  }
}

const user = User.of(`Adam`, `Bartonicek`);

user.firstName = `Bob`
console.log(user)
console.log(user.lastName);
console.log(User.getFullName(user));
```

Clearly, it is possible to encapsulate data while maintaining separation between data and code. Specifically, the data underpinning `User` is still a plain data object and can be inspected using `console.log`. However, we cannot access or modify its properties outside of the `User` code module.

## Gauss method and the russian peasant algorithm for monoids {#gauss-russian-monoids}

Assume we have a commutative monoid $(M, e, \otimes)$ and a sequence $s$ obtained by repeatedly taking a product of an element $a \in M$ with some fixed increment $b \in M$, such that $s = (a, (a \otimes b), (a \otimes b \otimes b), \ldots)$. If we want to reduce $s$ into a total product $p$ by repeatedly applying the operation $\otimes$, i.e. $p = a \otimes (a \otimes b) \otimes (a \otimes b \otimes b) \otimes \ldots$, then we can use commutativity and associativity to rearrange the expression in the following way:

\begin{align}
p &= a \otimes (a \otimes b) \otimes (a \otimes b \otimes b) \otimes \ldots \\
&= (a \otimes b^0) \otimes  (a \otimes b^1) \otimes (a \otimes b^2) \otimes \ldots \otimes \otimes (a \otimes b^{n - 1}) \otimes (a \otimes b^n) \\
&= [(a \otimes b^0) \otimes (a \otimes b^n)] \otimes [(a \otimes b^1) \otimes (a \otimes b^{n - 1})] \otimes \ldots \\ 
&= [a \otimes (a \otimes b^n)]^{n / 2} \\
&= d^{n / 2}
\end{align}

Where $d = a \otimes (a \otimes b^n)$ is just the product of the first and the last elements in the sequence, respectively. This echoes the Gauss method of summing arithmetic series, although in that case, the repeated operations (sums) can be simplified even further, by relating sums to products ($(1 + n)^{n / 2} = [n(n + 1)] / 2$). Here, we may not necessarily have a way to simplify repeated products, however, since $d$ is fixed, we can use the Russian peasant algorithm to compute the total product in $O(\log n)$ time via squaring:

```{r}
#| results: 'hold'
russian_peasant <- function(x, fn, e, n) {
  result <- e

  while (n > 0) {
    if (n %% 2 != 0) result <- fn(result, x)
    n <- floor(n / 2)
    x <- fn(x, x)
  }

  result
}

reduce_sequence <- function(x, fn, e) {
  d <- fn(x[1], x[length(x)])
  n <- floor(length(x) / 2)
  russian_peasant(d, fn, e, n)
}

x <- 1:8
sum(x)
reduce_sequence(x, sum, 0)

x <- 2^(1:8)
prod(x)
reduce_sequence(x, prod, 1)
```


