# Conclusion

This thesis explored algebraic relationships underlying interactive data visualization pipelines. Specifically, it investigated the intricate interplay between data, summary statistics, graphics, and interaction. A recurring central theme has been that what we compute (statistics), how we represent it (graphics), and what we do with it (interaction) are not independent concerns. Instead, for graphics to behave well, particularly under interaction, their components need to exhibit a particular kind of congruence, which can be described via the language of category theory. 

This perspective challenges the presently dominant approach in data visualization. In many popular data visualization packages, graphics and statistics (and interaction) are treated as independent, modular components. However, I believe I have been able to demonstrate that this independence model is insufficient for reasoning about visualizations comprehensively, and can lead to meaningless, "bizarre or degenerate" graphics. By contrast, the model I propose allows us to identify those combinations of graphics and statistics which will be meaningful, by virtue of composition, and those which will be degenerate or bizzare, due to lack thereof. Further, it also allows us to reason about when certain types of interactions, particularly linked selection, will combine with the graphic to produce certain predictable, natural results.

Further, I also tested and refined many of the ideas surrounding the model by developing an original interactive data visualization library for R: `plotscaper`. Beyond theory testing, `plotscaper` was developed to provide a practical tool for data exploration, a goal which appears to have been achieved with moderate success, as evidence by the package's download statistics in the relatively short time interval since its initial release. Developed largely from scratch and with minimal dependencies, the creation of the `plotscaper` necessitated the resolution of numerous fundamental programming issues and architectural concerns. Many of these challenges and their solutions are also documented throughout this thesis, with the goal of providing directions for potential future research and development.

In conclusion, I find the algebraic structure of data visualizations and its relationship to interactivity to be a fascinating topic. I consider myself lucky to have stumbled upon few intriguing ideas that allowed me to see graphics in an entirely new light. Yet, I recognize that the model presented in this thesis is far from exhaustive, and significant opportunities remain for future research. Since the model is built on some simple, foundational concepts from category theory, it is natural to assume that category theory may yield many further, much deeper insights regarding the nature of the relationships between graphics, statistics, and interaction. Nevertheless, I hope it is clear that even these simple ideas provide a powerful tool for reasoning about graphics and even possess a significant applied utility. Ultimately, developing truly generic and robust interactive data visualization systems may require grappling with these ideas further.
